import './mobile-menu.js';
import './modal-order-now.js';
import './hero-api.js';
import './favorite-recipes.js';
import './dark-theme.js';
import './categories.js';
import './modal-recipe.js';
import './filter.js';
import './modal-ratio';
